### ISSUE TITLE
Missing ? when adding querystring to URL

### ISSUE THREAD

**Issue by stehefan** [1000ch/node-speedcurve#1]
Hej there,

I was just using your package, but the URL that it's using when e.g. querying for all sites, I get a wrong URL for the querying. It is missing the `?` between the URL and the query-parameters.

Wrong: 
```
https://api.speedcurve.com/v1/sitesformat=speedcurve&days=14
```

Correct:
```
https://api.speedcurve.com/v1/sites?format=speedcurve&days=14
```

I'll file a PR for fixing this. 

My setup:
node-version 5.8.0
got-version: 6.3.0

**Comment by 1000ch** [comment]
Fixed in `v0.3.0`. Thank you.
